#!/bin/bash

git submodule update --init --recursive
cd src/submodules

echo Building json-fortran

cd json-fortran
mkdir build
cd build
cmake -D CMAKE_INSTALL_PREFIX=../../bin/ -D SKIP_DOC_GEN=TRUE ..
cmake --build .
cmake --install .
cd ..
rm -r -d build
cd ..

echo Building pfUnit

cd pFUnit
mkdir build
cd build
cmake -D CMAKE_INSTALL_PREFIX=../../bin/ ..
cmake --build .
cmake --install .
cd ..
rm -r -d build

