#!/bin/bash

cd src/submodules

echo Building json-fortran

cd json-fortran
mkdir build
cd build
pwd
cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/.local/bin/
cmake .. -DSKIP_DOC_GEN=TRUE
cmake --build .
cmake --install .
cd ..
rm -r -d build
cd ..

echo Building pfUnit

cd pFUnit
mkdir build
cd build
pwd
cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/.local/bin/
cmake --build .
cmake --install .
cd ..
rm -r -d build

